/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    AssetRegistry: {
      address: "0x3F536A2a22fF1D99F6b08b72FE4A9aDE8DC07652",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "guardian_",
              type: "address",
            },
            {
              internalType: "contract InvestorRegistry",
              name: "investors_",
              type: "address",
            },
            {
              internalType: "uint64",
              name: "lockupPeriod_",
              type: "uint64",
            },
            {
              internalType: "address",
              name: "htsPrecompile",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "responseCode",
              type: "int64",
            },
          ],
          name: "HtsError",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "lockupEnds",
              type: "uint64",
            },
          ],
          name: "LockupActive",
          type: "error",
        },
        {
          inputs: [],
          name: "NotFinalized",
          type: "error",
        },
        {
          inputs: [],
          name: "NotGuardian",
          type: "error",
        },
        {
          inputs: [],
          name: "NotIssuer",
          type: "error",
        },
        {
          inputs: [],
          name: "NotVerifiedInvestor",
          type: "error",
        },
        {
          inputs: [],
          name: "UnknownAsset",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "enum AssetRegistry.Status",
              name: "expected",
              type: "uint8",
            },
            {
              internalType: "enum AssetRegistry.Status",
              name: "actual",
              type: "uint8",
            },
          ],
          name: "WrongStatus",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAddress",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "investor",
              type: "address",
            },
          ],
          name: "AssetEnabled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "cid",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "documentHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "shares",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "topicId",
              type: "uint64",
            },
          ],
          name: "AssetSubmitted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "attester",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "approve",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "evidenceHash",
              type: "bytes32",
            },
          ],
          name: "Attested",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "pair",
              type: "address",
            },
          ],
          name: "Finalized",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "lockupEnds",
              type: "uint64",
            },
          ],
          name: "MintConfirmed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
          ],
          name: "Paused",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "TokenRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
          ],
          name: "Unpaused",
          type: "event",
        },
        {
          inputs: [],
          name: "assetCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "approve",
              type: "bool",
            },
            {
              internalType: "bytes32",
              name: "evidenceHash",
              type: "bytes32",
            },
          ],
          name: "attest",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
          ],
          name: "confirmMint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
          ],
          name: "enableAsset",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "pair",
              type: "address",
            },
          ],
          name: "finalize",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
          ],
          name: "getAsset",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "issuer",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "token",
                  type: "address",
                },
                {
                  internalType: "bytes32",
                  name: "documentHash",
                  type: "bytes32",
                },
                {
                  internalType: "string",
                  name: "cid",
                  type: "string",
                },
                {
                  internalType: "uint64",
                  name: "shares",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "topicId",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "lockupEnds",
                  type: "uint64",
                },
                {
                  internalType: "enum AssetRegistry.Status",
                  name: "status",
                  type: "uint8",
                },
              ],
              internalType: "struct AssetRegistry.Asset",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "guardian",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "hasAttested",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "investors",
          outputs: [
            {
              internalType: "contract InvestorRegistry",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "lockupPeriod",
          outputs: [
            {
              internalType: "uint64",
              name: "",
              type: "uint64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
          ],
          name: "pause",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "registerToken",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "cid",
              type: "string",
            },
            {
              internalType: "bytes32",
              name: "documentHash",
              type: "bytes32",
            },
            {
              internalType: "uint64",
              name: "shares",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "topicId",
              type: "uint64",
            },
          ],
          name: "submitAsset",
          outputs: [
            {
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "assetId",
              type: "uint256",
            },
          ],
          name: "unpause",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40855983,
    },
    InvestorRegistry: {
      address: "0xDA604dD18c0dC46ee09CBD20cECdEc51d87Cd36f",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "admin_",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "NotAdmin",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAddress",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousAdmin",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newAdmin",
              type: "address",
            },
          ],
          name: "AdminTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "investor",
              type: "address",
            },
          ],
          name: "InvestorApproved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "investor",
              type: "address",
            },
          ],
          name: "InvestorRevoked",
          type: "event",
        },
        {
          inputs: [],
          name: "admin",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "investor",
              type: "address",
            },
          ],
          name: "approve",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "isVerified",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "investor",
              type: "address",
            },
          ],
          name: "revoke",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newAdmin",
              type: "address",
            },
          ],
          name: "transferAdmin",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40855979,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
